# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Max Leow
title: Senior Test Automation Engineer
email: maxengiu@outlook.com
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  maxlinux
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: max-eng-iu-leow-a055b912
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Max and I'm a senior test automation engineer.  
  I like to build tools/libraries to solve my job's problems, it is exciting to watch how my solution fits in.  
  I am working on data analysis and visualization for quality reports and observations for problem-solving.  
  On top of that, I have cumulated years of experience in building and designing an in-house Selenium library as well as Jenkins pipeline with Ansible and Chef.
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
          title: Testrail data
          link: github.com/maxleow/testrail_data
          additional_links:
            - title:  maxleow/testrail_data
              icon: fab fa-github
              url: https://github.com/maxleow/testrail_data
          quote: >
            Handy library for retrieving big results
          description: | # this will include new lines to allow paragraphs
            This library is trying to create a convenient way of pulling the results and case info from 
            Testrails(A Test management system) for analytic purposes. 
            With the help of [Pandas](https://github.com/pandas-dev/pandas), we are gaining flexibility and speed in exploring the data.
      - layout: top-middle
        title: Helical railgun
        link: github.com/achelois-armoury/helical-railgun
        # link_text: Project Website
        additional_links:
          - title:  achelois-armoury/helical-railgun
            icon: fab fa-github
            url: https://github.com/maxlinux
        quote: >
          Let every unit-test count
        description: | # this will include new lines to allow paragraphs
          I started this project during a hackathon event. We are using [Testrail](https://www.gurock.com/testrail/) 
          as our [Test Oracle](https://en.wikipedia.org/wiki/Test_Oracle). To publish the results, it often troublesome
          due to some dependencies behind the pipelines, which can be simplify through this solution.
      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Experian 
        link: experian.com
        # link_text: boringcompany.com
        sub_title: Senior QA Engineer
        caption: November 2013 - Present
        description: | # this will include new lines to allow paragraphs
            ## 2020 - Present (QA)
            
            Consolidating test results and visualized into interactive charts, 
            grouping by products, groups, teams, priorities in a time series manner.
            Tools and libraries I was using 
            <mark>AWS EC2 instance</mark> for api hosting, 
            <mark>Python 3.7</mark> to aggragate results and as a REST server, 
            <mark>EazyBI</mark> to Data visualization plugin,
            <mark>Bitbucket</mark> as a storage and 
            <mark>Terraform</mark> for deployment.

            ----------------------    

            ## 2018 - 2020 (QA)
            
            Design, implement and maintain product provisionining scripts using 
            <mark>Ansible</mark>, <mark>Packer</mark> and Terraform for the entire 
            test automation pipelines. Promoting component testing as a left shift strategy.

            -------------------
            
            ## 2016 - 2018 (QA)
            
            Leading <mark>Cucumber</mark> and <mark>Selenium</mark> projects development, such as 
            coaching, library development, Writting [CHEF](https://www.chef.io/) recipe, 
            preparing process and best practices for all the scrum teams.

            -------------------

            ## 2015 - 2016 (QA)
            
            Supervising automation test out-sourcing written in <mark>QFTest</mark>, 
            review, verify and facilitate the vendor to contribute 
            seamlessly.

            --------------------


            ## 2013 - 2014 (Developer)  
            
            Responsible for implementing features into 
            [PCO](https://www.experian.com/business/products/powercurve-originations) 
            (Powercurve Origination). 
            Have joined a scrum team for more than a year. 
            The first person who implemented a new platform(RHEL) supported PCO (BPS, Web Engine).

            --------------------------
      - layout: left
        title: Openet
        link: openet.com
        # link_text: boringcompany.com
        sub_title: Software Design Engineer
        caption: November 2010 - 2013
        description: | # this will include new lines to allow paragraphs
            ## 2012 - 2013 
            
            PCEF (policy charging enforcement function) is an element mainly used by the Telecommunication 
            industry. Since the PCRF software is implemented against the standard defined by 
            3GPP(3rd Generation Partnership Project), requirement for shipping user interface to 
            different PCEF vendors is important. 
            I am responsible for developing a Web base configuration system to manage 
            the rule configuration on PCRF.

            -------------------------

            ## 2011-2012 
            
            Openet Installation Framework. It is a command based framework that deploys components 
            to multiple platforms. It also summarized methods and ways of component installations 
            into one package. My responsibility is to maintain and gather the requirements to 
            enhance the framework to be able support multiple platform deployment.

            --------------------------

            ## 2010-2011 
            
            Automated test framework. It is used by engineering to automate deployment and testing. 
            My responsibilities are to add a Web base testing using Selenium library into this framework.
            
            --------------------------

            ## Skill set: 

            JBOSS application server, Maven, EJB3.0, Hibernate 3.0, SEAM, GWT(Google Web Toolkit), 
            HTML, Java script, Selenium web automation test,  JSF2.0, ORACLE 11g, H2 Database.


            ## Platforms:

            RHE6, HP-Unix, Sun Solaris SPARC, Sun Solaris x86.

            ------------------------------
      
      - layout: left
        title: Amdocs Changing Worlds Malaysia
        link: changingworlds.com
        # link_text: boringcompany.com
        sub_title: Software Design Engineer
        caption: 2008 - 2010
        description: | # this will include new lines to allow paragraphs

            ## 2009 - 2010 

            Maintaining existing product, Device Description Repository(DDR), 
            Used to collect latest mobile devices specification 
            information from UAProf and WURFL and host as application server for Telecommunication 
            company Wap Portal. 

            -----------------------------

            ## 2008 - 2009 

            Maintaining existing product, XSL IDE, is a proprietery IDE to do with Extensible Style Language (XSL). 
            A new copy of XSL will be generated after retrieving information from DDR. 
            The xsl then will be passed to a translation engine to translate a best viewed HTML or WAP 
            page for a particular mobile device that is visiting the portal. 
            For the sake of easy maintenance and time saving, XSL IDE is created. 
            It produces a startup template and graphical based tree view to edit a XSL document. 
            XSL IDE is implementing a generic Swing IDE platform which we are using Netbeans Platform.
            WAP portal can be accessed by phone’s browser with internet connection. 
            Non-OS based Phone has smaller screen sizes and limited contents to be displayed. 
            Solution to create a presentation framework to work with mobile devices was essential.  
            User preferences theming and shorten the interaction during content rendering. 
            This application allows users to do exactly like a social networking website, l
            ike make friends, comment, send messages in mobile phones. 

            ----------------------

            ## Skill set:

            JAVA SE, XSL2.0, Netbeans Platform, Spring core, Spring-mvc, 
            Javascript, jQuery, Javascript, SQL, PHP, PLSQL, Axis2
            
            ## Platforms: 

            RHE4, Solaris SPARC 5.5, Tomcat 5, IBM Websphere 5, Oracle Weblogic 4
            
            ## Database:
            Oracle 10g, MySQL

      - layout: left
        title: Ionnex Sdn Bhd
        link: ionnex.com
        sub_title: Mobile software developer
        caption: 2005 - 2008
        description: | # this will include new lines to allow paragraphs
            ## 2005 - 2008 
            > Develop and design Instant Messenger Application for mobile phone which connects to MSN, 
            Yahoo, Gtalk and Device Profiler Application.

            Mobile Phone Communication system.  The application consists of server and client.  
            Server required to hold socket connections from clients and establishes messenger 
            sessions to messenger providers (MSN, Yahoo etc). 
            Client was developed by J2ME to support most phones in the market with a single set of source code. 
            We were implementing a dynamic native Graphic User Interface (GUI) which can populate a set 
            of GUI that suite all devices. Reason of using native graphics is to present an interactive, 
            attractive and cool interface like we have in game applications.

            -------------------------

            ## Skills set involved:

            J2ME, Java SE, Microsoft ASP.NET 2.0
            
            ## Database:
            
            MySQL, Microsoft SQL Server 2000

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Universiti Tunku Abdul Rahman
        caption: 2003 - 2005
        sub_title: BSc Computer Science
        
      - layout: top-middle
        title: Tunku Abdul Rahman University College
        caption: 2001 - 2003
        sub_title: Diploma in Science
          
  - title: Certifications
    layout: list
    content:
      - layout: top-middle
        title: Probability Theory, Statistic and Exploratory Data Analysis
        caption: Issued Sep 2020
        sub_title: Coursera
        link: https://www.coursera.org/account/accomplishments/certificate/PQF7EHSKPVSV

      - layout: top-middle
        title: Certified Testers Foundation Level (CTFL)
        caption: Issued Aug 2019
        sub_title: ISTQB - International Software Testing Qualifications Board
        link: https://www.mstb.org/CTFL.php
        quote: > 
          MY0037-19
        
  - title: More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      As a father of 3, with the remaining fractual time, I still find myself enjoy doing:
      - Baduk/Go board game
      - Running
      - [Photographing](https://www.instagram.com/engiumax/) 
    
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
